version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pcpr-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hljt8jn3qide"
s3_prefix = "pcpr-sam"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
