AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pcpr-sam-test

  Sample SAM Template for pcpr-sam-test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  PcprSamFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: pcpr_generator/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PcprSamFunction:
    Description: "PCPR conversion Lambda built via SAM"
    Value: !GetAtt PcprSamFunction.Arn
  PcprSamFunctionIamRole:
    Description: "Implicit IAM Role created for PcprSamFunction function"
    Value: !GetAtt PcprSamFunctionRole.Arn
